# Generated by Django 5.2.4 on 2025-07-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_restaurant_options_menuitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/profilepictures/'),
        ),
    ]
