# Generated by Django 5.2.4 on 2025-07-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cart_total_price_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
