# Generated by Django 5.2.4 on 2025-07-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_menuitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='default_images/default_profile_picture.jpg', null=True, upload_to='images/menu/'),
        ),
    ]
